### ISSUE TITLE
非本地socks5代理nat type 检测不成功

### ISSUE THREAD

**Issue by RTM945** [NetchX/Netch#1030]
### 错误描述

非本地socks5代理nat type 检测不成功

### 复现步骤

简单复现方式：
创建一个外网的socks代理，用nattypetester检测fullcone，配进netch代理任意程序

一直显示 NAT：Testing Nat Type
点击报错如下

### 日志

A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at Socks5.Clients.Socks5Client.UdpAssociateAsync(IPAddress address, UInt16 port, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at Socks5.Clients.Socks5Client.SendCommandAsync(IDuplexPipe pipe, Command command, String dst, IPAddress dstAddress, UInt16 dstPort, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at Pipelines.Extensions.PipelinesExtensions.ReadAsync(PipeReader reader, HandleReadOnlySequence func, CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.IO.Pipelines.Pipe.ExecuteWithoutExecutionContext(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Netch.Program.Main(String[] args)
--- End of stack trace from previous location ---
   at Socks5.Clients.Socks5Client.UdpAssociateAsync(IPAddress address, UInt16 port, CancellationToken token)
   at STUN.Proxy.Socks5UdpProxy.ConnectAsync(CancellationToken cancellationToken)
   at STUN.Client.StunClient5389UDP.ConnectProxyAsync(CancellationToken cancellationToken)
   at Netch.Utils.Socks5ServerTestUtils.DiscoveryNatTypeAsync(Socks5Server socks5, CancellationToken ctx)
   at Netch.Forms.MainForm.DiscoveryNatTypeAsync()
   at Netch.Forms.MainForm.NatTypeStatusLabel_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

### 操作环境

```txt
操作系统
Edition	Windows 10 Pro
Version	20H2
Installed on	‎13/‎03/‎2021
OS build	19042.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0
软件版本
1.9.7
```

### 额外信息
替换过很多stun服务器，依然不成功
_No response_

**Comment by qxsyb** [comment]
我也遇到了同样的问题，貌似是dns的问题。更改本地dns后，虽然还是不显示nat类型，但是已经可以正常连接外网。

**Comment by starmoon-1134** [comment]
+1
socks5代理服务器用的sing-box，从日志看，接收的tcp请求目标地址是正确的。
但是udp目标地址是127.0.0.1

tcp日志：
+0800 2023-04-22 10:42:03 INFO [2447922068 0ms] inbound/mixed[mixed-in]: inbound connection from 192.168.0.104:4963
+0800 2023-04-22 10:42:03 INFO [2447922068 2ms] inbound/mixed[mixed-in]: inbound connection to cp.cloudflare.com:80
+0800 2023-04-22 10:42:03 INFO [2447922068 320ms] outbound/vless[aws-vless-cdf]: outbound connection to cp.cloudflare.com:80

udp日志：
+0800 2023-04-22 10:42:06 INFO [1293299118 0ms] inbound/mixed[mixed-in]: inbound connection from 192.168.0.104:4964
+0800 2023-04-22 10:42:06 INFO [1293299118 2ms] inbound/mixed[mixed-in]: inbound packet connection to 127.0.0.1:57851

**Comment by starmoon-1134** [comment]
有人提过这个问题了，并给出了解决方案，需要自行修改代码、编译 [issues813](https://github.com/netchx/netch/issues/813)
