### ISSUE TITLE
1.9.7版本创建进程模式无法启动

### ISSUE THREAD

**Issue by Chinakentgao** [NetchX/Netch#1103]
### Describe the bug

启动就报错。刚装的新电脑最新W11就出来这个问题。管理员模式关闭杀软都试过不行。

### To Reproduce

1.打开netch
2.创建进程模式
3.输入进程名
4.保存
5.启动

### Log

[2023-11-22 21:17:27][Information] Netch Version: NetchX/Netch@1.9.7
[2023-11-22 21:17:27][Information] OS: Microsoft Windows NT 10.0.22631.0
[2023-11-22 21:17:28][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2023-11-22 21:17:28][Information] System Language: zh-CN
[2023-11-22 21:17:29][Information] Github latest release: 1.9.7
[2023-11-22 21:17:29][Information] Already the latest version
[2023-11-22 21:17:29][Debug] Third-party Drivers:
Lenovo Virtual Power Controller Driver [Lenovo Virtual Power Controller Driver]()
	C:\Windows\system32\drivers\AcpiVpc.sys
VMware hcmon [VMware hcmon](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\hcmon.sys
hotfixplatform [hotfixplatform]()
	\??\C:\Windows\system32\drivers\hotfixplatform.sys
IndexProtect [IndexProtect]()
	C:\Windows\system32\DRIVERS\IndexProtect.sys
LnvDrvFdn [LnvDrvFdn](Copyright (C) 2023)
	C:\Windows\system32\DRIVERS\LnvDrvFdn.sys
LnvHelp [LnvHelp]()
	C:\Windows\system32\DRIVERS\LnvHelp.sys
lnvscenter [lnvscenter](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\lnvscenter.sys
lrtp [lrtp](LENOVO Corporation. All rights reserved.)
	C:\Windows\system32\DRIVERS\lrtp.sys
msrep [msrep](LENOVO Corporation. All rights reserved.)
	C:\Windows\system32\DRIVERS\msrep.sys
netfilter2 [netfilter2](Copyright ? NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
netrtp [netrtp](Copyright (C) 2019)
	C:\Windows\system32\DRIVERS\netrtp.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\drivers\vmci.sys
VMware Virtual Ethernet Adapter Driver [VMware Virtual Ethernet Adapter Driver](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetadapter.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetuserif.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2022 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmx86.sys
vSockets Virtual Machine Communication Interface Sockets driver [vSockets Virtual Machine Communication Interface Sockets driver](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vsock.sys
MpKslc236a1d7 [MpKslc236a1d7]()
	\??\C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{F545114D-B67B-456B-A7C2-4664ECF03238}\MpKslDrv.sys
[2023-11-22 21:17:30][Information] Start MainController: SS [0]vmware
[2023-11-22 21:17:30][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2023-11-22 21:17:31][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2023-11-22 21:17:31][Information] Installed netfilter2 driver version: 1.6.0.2
[2023-11-22 21:17:31][Information] Update netfilter2 driver
[2023-11-22 21:17:31][Information] Uninstall netfilter2
[2023-11-22 21:17:31][Information] Stop Main Controller
[2023-11-22 21:17:31][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)
[2023-11-22 21:17:32][Debug] Running Processes: 
C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
C:\Program Files (x86)\Google\Update\1.3.36.342\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.342\GoogleCrashHandler64.exe
C:\Program Files (x86)\Lenovo\baiying\byService.exe
C:\Program Files (x86)\Lenovo\LeAppStore\LeAppOM.exe
C:\Program Files (x86)\Lenovo\LeAppStore\LenovoServiceAS.exe
C:\Program Files (x86)\Lenovo\LenovoInternetSoftwareFramework\LenovoInternetSoftwareFramework.exe
C:\Program Files (x86)\Lenovo\LenovoInternetSoftwareFramework\LISFService.exe
C:\Program Files (x86)\Lenovo\Lsf\Lsf.exe
C:\Program Files (x86)\Lenovo\PCManager\5.1.30.9202\EMDriverAssist.exe
C:\Program Files (x86)\Lenovo\PCManager\5.1.30.9202\LenovoPcManagerService.exe
C:\Program Files (x86)\Lenovo\Smart Storage\SmartStorage.exe
C:\Program Files (x86)\Lenovo\Smart Storage\winspace.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\LenovoSmartService.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\SmartEngineHost.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\SmartEngineHost64.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\SmartEngineTray.exe
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\119.0.2151.72\msedgewebview2.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\Lenovo\AIMM Service PRC\Ammbkproc.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\IntelligentSensingAwareService\LsaRpcServer.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\IntelligentSensingAwareService\LsaServerPartner.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\IntelligentSensingAwareService\LsaToast.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\IntelligentSensingService\LsaApp.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\IntelligentSensingService\LsaIssRpcServer.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\SmartAppearanceAIService\FaceBeautify.exe
C:\Program Files\Lenovo\Lenovo Smart Meeting Components\Components\SmartAppearanceAIService\SmartAppearanceSVC.exe
C:\Program Files\Microsoft OfficePLUS\2.9.0.58602\service\MSOfficePLUSService.exe
C:\Program Files\Mozilla Firefox\firefox.exe
C:\Program Files\NVIDIA Corporation\NvBroadcast.NvContainer\NvBroadcast.Container.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
C:\Program Files\NVIDIA Corporation\ShadowPlay\nvsphelper64.exe
C:\Users\lenovo\AppData\Local\Microsoft\OneDrive\23.226.1031.0003\FileCoAuth.exe
C:\Users\lenovo\AppData\Local\Microsoft\OneDrive\OneDrive.exe
C:\Users\lenovo\AppData\Local\Tencent\QQGuild\9.7.19-437\QQGuild.exe
C:\Users\lenovo\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\RadiumWMPF\8461\extracted\runtime\WechatAppEx.exe
C:\Users\lenovo\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\RadiumWMPF\8461\extracted\runtime\WeChatAppEx.exe
C:\Users\lenovo\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\ThumbPlayer\4067\extracted\WeChatPlayer.exe
C:\Users\lenovo\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\WeChatOCR\7061\extracted\WeChatOCR.exe
C:\Users\lenovo\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\WeChatUtility\8085\extracted\WechatUtility.exe
D:\lx-music\lx-music-desktop.exe
e:\BaiduNetdisk\YunDetectService.exe
E:\Netch\Netch.exe
E:\Program Files (x86)\SogouInput\13.11.0.8646\SGTool.exe
e:\Program Files (x86)\SogouInput\13.11.0.8646\SogouCloud.exe
E:\Program Files (x86)\Tencent\QQ\Bin\QQ.exe
e:\Program Files (x86)\Tencent\QQ\Bin\TXPlatform.exe
E:\Program Files (x86)\VMware\VMware Workstation\vmware-authd.exe
E:\Program Files (x86)\VMware\VMware Workstation\vmware-tray.exe
E:\Program Files (x86)\VMware\VMware Workstation\vmware-unity-helper.exe
E:\Program Files (x86)\VMware\VMware Workstation\vmware.exe
E:\Program Files\Tencent\WeChat\[3.9.8.15]\mmcrashpad_handler64.exe
E:\Program Files\Tencent\WeChat\WeChat.exe
E:\Program Files\xbyyunpan\小白羊云盘.exe
E:\Program Files\xbyyunpan\resources\engine\alist.exe
E:\Program Files\xbyyunpan\resources\engine\aria2c.exe
E:\v2rayN-With-Core\bin\Xray\xray.exe
E:\v2rayN-With-Core\v2rayN.exe
[2023-11-22 21:17:58][Information] Uninstall netfilter2
[2023-11-22 21:17:58][Error] Unhandled error
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Netch.Forms.MainForm.UninstallServiceToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[2023-11-22 21:18:00][Information] Start MainController: SS [0]vmware
[2023-11-22 21:18:00][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2023-11-22 21:18:00][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2023-11-22 21:18:00][Information] Installed netfilter2 driver version: 1.6.0.2
[2023-11-22 21:18:00][Information] Update netfilter2 driver
[2023-11-22 21:18:00][Information] Uninstall netfilter2
[2023-11-22 21:18:00][Information] Stop Main Controller
[2023-11-22 21:18:00][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)

### Environment

```txt
Windows 11家庭中文版 23H2 22631.2715
netch 1.9.7
```

**Comment by Chinakentgao** [comment]
使用联想电脑的把联想相关的都关闭了，才能正常使用。
