### ISSUE TITLE
在WINDOWS上使用同一个网段的其他设备搭建SOCKS5代理服务器 一直显示测试NAT类型

### ISSUE THREAD

**Issue by YiGeRen-yl** [NetchX/Netch#1115]
### 错误描述

在WINDOWS上使用同一个网段下其他设备搭建的SOCKS5代理服务器 一直显示测试NAT类型

### 复现步骤

1.打开NETCH
2.添加同一网段下的其他设备的SOCKS5代理
3.启动NETCH.
4.NAT 显示正在测试NAT类型

### 日志

[2024-01-02 17:16:25][Error] Unhandled error
System.Net.Sockets.SocketException (10051): 向一个无法连接的网络尝试了一个套接字操作。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(IPAddress address, Int32 port, CancellationToken cancellationToken)
   at Socks5.Clients.Socks5Client.UdpAssociateAsync(IPAddress address, UInt16 port, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at Socks5.Clients.Socks5Client.SendCommandAsync(IDuplexPipe pipe, Command command, String dst, IPAddress dstAddress, UInt16 dstPort, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at Pipelines.Extensions.PipelinesExtensions.ReadAsync(PipeReader reader, HandleReadOnlySequence func, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.IO.Pipelines.Pipe.ExecuteWithoutExecutionContext(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Netch.Program.Main(String[] args)
--- End of stack trace from previous location ---
   at Socks5.Clients.Socks5Client.UdpAssociateAsync(IPAddress address, UInt16 port, CancellationToken token)
   at STUN.Proxy.Socks5UdpProxy.ConnectAsync(CancellationToken cancellationToken)
   at STUN.Client.StunClient5389UDP.ConnectProxyAsync(CancellationToken cancellationToken)
   at Netch.Utils.Socks5ServerTestUtils.DiscoveryNatTypeAsync(Socks5Server socks5, CancellationToken ctx)
   at Netch.Forms.MainForm.DiscoveryNatTypeAsync()
   at Netch.Forms.MainForm.NatTypeStatusLabel_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

### 操作环境

```txt
WIN10
```

### 额外信息

![image](https://github.com/netchx/netch/assets/75572420/1cbed9c9-db9e-436e-8cc7-274e7d62c131)

**Comment by MCsonger** [comment]
同问 使用socks5 无法成功代理UDP 导致无法加速游戏
经过测试 socks5在clash中代理 可以正常进行游戏游玩、但netch无法正常成功代理。
请问 这个问题是否能解决、同时也能希望可以解决这个问题
![image](https://github.com/netchx/netch/assets/59940656/db4cd962-8977-4ca2-a0c9-ddd28b4282ee)
