### ISSUE TITLE
显示Unhandled Exception

### ISSUE THREAD

**Issue by f1owerr** [NetchX/Netch#1123]
### Describe the bug

显示Unhandled Exception
Access to the path .. is denied

### To Reproduce

1.打开Netch
2.选择一个模式
3.启动

### Log

[2024-02-04 14:35:00][Information] Netch Version: NetchX/Netch@1.9.7
[2024-02-04 14:35:00][Information] OS: Microsoft Windows NT 10.0.22621.0
[2024-02-04 14:35:00][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2024-02-04 14:35:00][Information] System Language: zh-CN
[2024-02-04 14:35:01][Debug] Third-party Drivers:
Lenovo Virtual Power Controller Driver [Lenovo Virtual Power Controller Driver]()
	C:\Windows\system32\drivers\AcpiVpc.sys
Audio Coprocessr Driver for DSP [Audio Coprocessr Driver for DSP](Â© Advanced Micro Devices. All rights reserved.)
	C:\Windows\system32\DriverStore\FileRepository\amdacpbus.inf_amd64_1eee1ecba7bae5f4\amdacpbus.sys
AMD Audio Service [AMD Audio Service](© Advanced Micro Devices. All rights reserved.)
	C:\Windows\system32\DriverStore\FileRepository\amdacpafd.inf_amd64_dea03ff0fb4183f1\amdacpafd.sys
AMD Crash Defender Driver [AMD Crash Defender Driver](Copyright (C) 2021 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdfendr.sys
AMD Crash Defender Manager Driver [AMD Crash Defender Manager Driver](Copyright (C) 2021 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdfendrmgr.sys
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdgpio2.sys
AMD I2C Controller Service [AMD I2C Controller Service](Copyright © 2014-2022 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdi2c.sys
AMD Micro PEP Device [AMD Micro PEP Device](Copyright © Advanced Micro Devices, Inc. 2021)
	C:\Windows\system32\drivers\AmdMicroPEP.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2022 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdpsp.sys
amdwddmg [amdwddmg](Copyright (C) 1998-2012 Advanced Micro Devices, Inc.)
	C:\Windows\system32\DriverStore\FileRepository\u0390484.inf_amd64_630d985383d47087\B389503\amdkmdag.sys
AMD Function Driver for HD Audio Service [AMD Function Driver for HD Audio Service](© Advanced Micro Devices. All rights reserved.)
	C:\Windows\system32\drivers\AtihdWT6.sys
Genesys Logic PCIE card reader Service [Genesys Logic PCIE card reader Service](2023 Genesys Logic)
	C:\Windows\system32\drivers\GlPciSD.sys
hotfixplatform [hotfixplatform]()
	\??\C:\Windows\system32\drivers\hotfixplatform.sys
IndexProtect [IndexProtect]()
	C:\Windows\system32\DRIVERS\IndexProtect.sys
LnvDrvFdn [LnvDrvFdn](Copyright (C) 2023)
	C:\Windows\system32\DRIVERS\LnvDrvFdn.sys
LnvHelp [LnvHelp]()
	C:\Windows\system32\DRIVERS\LnvHelp.sys
lnvscenter [lnvscenter](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\lnvscenter.sys
lrtp [lrtp](LENOVO Corporation. All rights reserved.)
	C:\Windows\system32\DRIVERS\lrtp.sys
msrep [msrep](LENOVO Corporation. All rights reserved.)
	C:\Windows\system32\DRIVERS\msrep.sys
MTK BT Filter Driver [MTK BT Filter Driver](MediaTek Inc. (C)2019. All rights reserved.)
	C:\Windows\system32\DRIVERS\mtkbtfilterx.sys
Mediatek PCI LE Extensible Wireless LAN Card Driver [Mediatek PCI LE Extensible Wireless LAN Card Driver](MediaTek Inc. (C)2014. All rights reserved.)
	C:\Windows\system32\drivers\mtkwl6ex.sys
netfilter2 [netfilter2](Copyright ? NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
netrtp [netrtp](Copyright (C) 2019)
	C:\Windows\system32\DRIVERS\netrtp.sys
Leigod Network Technology LightWeight Filter [Leigod Network Technology LightWeight Filter](Leigod Network Technology Co., Ltd. 2022)
	C:\Windows\system32\DRIVERS\nnndisfilter.sys
Parade HID Device [Parade HID Device]()
	C:\Windows\system32\DriverStore\FileRepository\prhiddrv.inf_amd64_c3fefca1cacf90ce\PRHidDrv.sys
Parade SPB Peripheral Device [Parade SPB Peripheral Device]()
	C:\Windows\system32\drivers\PRSpbDrv.sys
TAP-Windows Adapter V9 [TAP-Windows Adapter V9](OpenVPN Technologies, Inc.)
	C:\Windows\system32\drivers\tap0901.sys
vgk [vgk]()
	\??\C:\Program Files\Riot Vanguard\vgk.sys
[2024-02-04 14:35:01][Debug] Running Processes: 
C:\Program Files (x86)\Google\Update\1.3.36.363\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.363\GoogleCrashHandler64.exe
C:\Program Files (x86)\Lenovo\LeAppStore\LeAppOM.exe
C:\Program Files (x86)\Lenovo\LeAppStore\LenovoServiceAS.exe
C:\Program Files (x86)\Lenovo\LenovoInternetSoftwareFramework\LenovoInternetSoftwareFramework.exe
C:\Program Files (x86)\Lenovo\LenovoInternetSoftwareFramework\LISFService.exe
C:\Program Files (x86)\Lenovo\Lsf\Lsf.exe
C:\Program Files (x86)\Lenovo\PCManager\5.1.50.13092\EMDriverAssist.exe
C:\Program Files (x86)\Lenovo\PCManager\5.1.50.13092\LenovoPcManagerService.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\LenovoSmartService.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\SmartEngineHost.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.70.10091\SmartEngineHost64.exe
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\120.0.2210.144\msedgewebview2.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\Lenovo\LVA PRC Service\VoiceAssistantService.exe
C:\Program Files\Microsoft Office\Root\Office16\SDXHelper.exe
C:\Program Files\Microsoft OfficePLUS\2.10.0.3731\service\MSOfficePLUSService.exe
D:\猫猫云\tidalab\猫猫云.exe
D:\猫猫云\tidalab\resources\libs\win32\clash.exe
D:\Netch\Netch\Netch.exe
[2024-02-04 14:35:02][Information] Github latest release: 1.9.7
[2024-02-04 14:35:02][Information] Already the latest version
[2024-02-04 14:35:02][Information] Start MainController: SS [0]Valorant
[2024-02-04 14:35:02][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2024-02-04 14:35:03][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2024-02-04 14:35:03][Information] Installed netfilter2 driver version: 1.6.0.2
[2024-02-04 14:35:03][Information] Update netfilter2 driver
[2024-02-04 14:35:03][Information] Uninstall netfilter2
[2024-02-04 14:35:03][Information] Stop Main Controller
[2024-02-04 14:35:03][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)
[2024-02-04 14:35:27][Information] Start MainController: SS [0]Valorant
[2024-02-04 14:35:27][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2024-02-04 14:35:27][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2024-02-04 14:35:27][Information] Installed netfilter2 driver version: 1.6.0.2
[2024-02-04 14:35:27][Information] Update netfilter2 driver
[2024-02-04 14:35:27][Information] Uninstall netfilter2
[2024-02-04 14:35:27][Information] Stop Main Controller
[2024-02-04 14:35:27][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)
[2024-02-04 14:36:14][Information] Start MainController: SS [0]Steam Games (with Steam)
[2024-02-04 14:36:14][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2024-02-04 14:36:14][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2024-02-04 14:36:14][Information] Installed netfilter2 driver version: 1.6.0.2
[2024-02-04 14:36:14][Information] Update netfilter2 driver
[2024-02-04 14:36:14][Information] Uninstall netfilter2
[2024-02-04 14:36:14][Information] Stop Main Controller
[2024-02-04 14:36:14][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)
[2024-02-04 14:36:20][Information] Start MainController: SS [0]Valorant
[2024-02-04 14:36:20][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2024-02-04 14:36:20][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2024-02-04 14:36:20][Information] Installed netfilter2 driver version: 1.6.0.2
[2024-02-04 14:36:20][Information] Update netfilter2 driver
[2024-02-04 14:36:20][Information] Uninstall netfilter2
[2024-02-04 14:36:20][Information] Stop Main Controller
[2024-02-04 14:36:20][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)
[2024-02-04 14:41:19][Information] Start MainController: SS [0]Valorant
[2024-02-04 14:41:19][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2024-02-04 14:41:19][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2024-02-04 14:41:19][Information] Installed netfilter2 driver version: 1.6.0.2
[2024-02-04 14:41:19][Information] Update netfilter2 driver
[2024-02-04 14:41:19][Information] Uninstall netfilter2
[2024-02-04 14:41:19][Information] Stop Main Controller
[2024-02-04 14:41:19][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)

### Environment

```txt
Windows 11
Netch 1.9.7
```

**Comment by YZLCQX** [comment]
You used leigod accelerator or other accelerator, check whether a network accelerator is installed. After uninstalling it try
