### ISSUE TITLE
The system cannot find the file specified (v1.7.6)

### ISSUE THREAD

**Issue by OneHappyForever** [netchx/netch#527]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**

When clicking "start", an error box pops up saying "The system cannot find the file specified"

**To Reproduce**

1. Open Netch
2. Select a Vmess server (it works in previous versions with the same options)
3. Select Web Proxy Bypass Lan
4. Click " Start "

**Log**
Attaching any log files in the folder `Netch\logging` is strongly recommended.

[2/27/2021 7:37:03 PM][INFO] Github 最新发布版本: 1.7.6
[2/27/2021 7:37:03 PM][INFO] 目前是最新版本
[2/27/2021 7:37:06 PM][INFO] 启动主控制器: VMess [3][Web Proxy] Bypass LAN
[2/27/2021 7:37:09 PM][ERROR] System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Netch.Controllers.Guard.StartInstanceAuto(String argument, ProcessPriorityClass priority)
   at Netch.Controllers.HTTPController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Netch.Controllers.MainController.<Start>d__19.MoveNext()
[2/27/2021 7:37:26 PM][INFO] 启动主控制器: VMess [3][Web Proxy] Bypass LAN
[2/27/2021 7:37:26 PM][ERROR] System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Netch.Controllers.Guard.StartInstanceAuto(String argument, ProcessPriorityClass priority)
   at Netch.Controllers.HTTPController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Netch.Controllers.MainController.<Start>d__19.MoveNext()

------

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows 10
- Netch Version: 1.7.6

**Additional context**

**Comment by testermania** [comment]
Netch CI #620

Welcome to trojan 1.16.0
[2021-03-01 14:15:10] [FATAL] fatal: ..\data\last.json: cannot open file
[2021-03-01 14:15:10] [FATAL] exiting. . . 
Welcome to trojan 1.16.0
