### ISSUE TITLE
请求的协议还没有在系统中配置，或者没有它存在的迹象。

### ISSUE THREAD

**Issue by devnakx** [netchx/netch#613]
### Describe the bug

启动失败
点击启动后提示“请求的协议还没有在系统中配置，或者没有它存在的迹象。”

### To Reproduce

点击启动后提示“请求的协议还没有在系统中配置，或者没有它存在的迹象。”
![issue](https://user-images.githubusercontent.com/38558065/114117918-41f97900-991a-11eb-8099-f230eec573b8.png)

### CAPTCHA

I am human

### Log

```shell
[2021/4/9 9:46:48][INFO] 版本: NetchX/Netch@1.8.3
[2021/4/9 9:46:48][INFO] 主程序 SHA256: a727e7c99c5c208cf97216ae59c6f640ad0fb73316ce61f7661ee885ef483495
[2021/4/9 9:46:50][INFO] Github 最新发布版本: 1.8.3
[2021/4/9 9:46:50][INFO] 目前是最新版本
[2021/4/9 9:47:23][INFO] 启动主控制器: SSR [2]Bypass LAN and China
[2021/4/9 9:47:24][INFO] 出口 网关 地址：192.168.8.1
[2021/4/9 9:47:24][INFO] 出口适配器：以太网 {A215BB17-399D-4FE6-B69C-63DF2D4E0CD3} Realtek PCIe 2.5GbE Family Controller, index: 19
[2021/4/9 9:47:24][INFO] 自带 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/9 9:47:24][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/9 9:47:28][ERROR] System.Net.NetworkInformation.NetworkInformationException (10043): 请求的协议还没有在系统中配置，或者没有它存在的迹象。
   at System.Net.NetworkInformation.SystemIPInterfaceProperties.GetIPv4Properties()
   at Netch.Models.TunAdapter.<.ctor>b__0_0(NetworkInterface i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Netch.Models.TunAdapter..ctor()
   at Netch.Controllers.TUNController.Start(Mode& mode)
   at Netch.Controllers.TUNController.Netch.Controllers.IModeController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at Netch.Controllers.MainController.Start(Server server, Mode mode)
```

### Environment

Windows 10 Pro x64 20H2
Netch v1.8.3

**Comment by devnakx** [comment]
还有我刚刚用中文的那个”错误报告“提交几次issue都直接http error 404了，很奇怪……

**Comment by devnakx** [comment]
还有以前的几个模式”[Non Web Proxy]“和”[Web Proxy]“都不见了，只能用TUN模式，是Netch以后不支持了吗？用旧版本的txt放到mode目录也无法识别使用

**Comment by ghost** [comment]
1. 模式 `[3] Bypass LAN and China` 测试正常
2. 以后 **可能** 没有 `Web Proxy` 了

**Comment by devnakx** [comment]
越更越难用，难以理解

**Comment by ghost** [comment]
仔细看看 commit 历史，中间很多更新我都没参与（

**Comment by ghost** [comment]
这锅我不背

**Comment by MasterOfStar** [comment]
> 1. 模式 `[3] Bypass LAN and China` 测试正常
> 2. 以后 **可能** 没有 `Web Proxy` 了

为啥会取消Web Proxy 难以理解
