### ISSUE TITLE
请求的协议还没有在系统中配置，或者没有它存在的迹象

### ISSUE THREAD

**Issue by dongzhaosheng73** [netchx/netch#630]
### 错误描述

[2021/4/29 23:13:03][INFO] 版本: NetchX/Netch@1.8.3
[2021/4/29 23:13:03][INFO] 主程序 SHA256: a727e7c99c5c208cf97216ae59c6f640ad0fb73316ce61f7661ee885ef483495
[2021/4/29 23:13:04][INFO] Github 最新发布版本: 1.8.3
[2021/4/29 23:13:04][INFO] 目前是最新版本
[2021/4/29 23:13:07][INFO] 启动主控制器: SS [1]Destiny 2 - Tencent
[2021/4/29 23:13:07][INFO] 出口 网关 地址：192.168.50.1
[2021/4/29 23:13:07][INFO] 出口适配器：以太网 {96E225B5-CFE7-4968-8EAB-C158A2DB97BC} Realtek PCIe GbE Family Controller, index: 8
[2021/4/29 23:13:07][INFO] 自带 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/29 23:13:07][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/29 23:13:07][ERROR] System.Net.NetworkInformation.NetworkInformationException (10043): 请求的协议还没有在系统中配置，或者没有它存在的迹象。
   at System.Net.NetworkInformation.SystemIPInterfaceProperties.GetIPv4Properties()
   at Netch.Models.TunAdapter.<.ctor>b__0_0(NetworkInterface i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Netch.Models.TunAdapter..ctor()
   at Netch.Controllers.TUNController.Start(Mode& mode)
   at Netch.Controllers.TUNController.Netch.Controllers.IModeController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at Netch.Controllers.MainController.Start(Server server, Mode mode)

### 复现步骤

启动tun模式失败

### 日志

[2021/4/29 23:13:03][INFO] 版本: NetchX/Netch@1.8.3
[2021/4/29 23:13:03][INFO] 主程序 SHA256: a727e7c99c5c208cf97216ae59c6f640ad0fb73316ce61f7661ee885ef483495
[2021/4/29 23:13:04][INFO] Github 最新发布版本: 1.8.3
[2021/4/29 23:13:04][INFO] 目前是最新版本
[2021/4/29 23:13:07][INFO] 启动主控制器: SS [1]Destiny 2 - Tencent
[2021/4/29 23:13:07][INFO] 出口 网关 地址：192.168.50.1
[2021/4/29 23:13:07][INFO] 出口适配器：以太网 {96E225B5-CFE7-4968-8EAB-C158A2DB97BC} Realtek PCIe GbE Family Controller, index: 8
[2021/4/29 23:13:07][INFO] 自带 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/29 23:13:07][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/29 23:13:07][ERROR] System.Net.NetworkInformation.NetworkInformationException (10043): 请求的协议还没有在系统中配置，或者没有它存在的迹象。
   at System.Net.NetworkInformation.SystemIPInterfaceProperties.GetIPv4Properties()
   at Netch.Models.TunAdapter.<.ctor>b__0_0(NetworkInterface i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Netch.Models.TunAdapter..ctor()
   at Netch.Controllers.TUNController.Start(Mode& mode)
   at Netch.Controllers.TUNController.Netch.Controllers.IModeController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at Netch.Controllers.MainController.Start(Server server, Mode mode)

### 操作环境

```txt
win10 10.0.18363
x64
```

### 额外信息

似乎是权限不足无法创建tun网卡

**Comment by dongzhaosheng73** [comment]
https://git.zx2c4.com/wintun/commit/?id=cef79225560bd454cb5c49d8d2b0cfac869de8d3  tun驱动这个版本的时候加了一个ElevateToSystem的判断 
其中在获取winlogon.exe程序句柄的时候用 PROCESS_QUERY_INFORMATION OpenProcess 会报无权限
https://stackoverflow.com/questions/28303436/openprocess-access-denied-error-only-on-windows-8-1
如果用private const uint MAXIMUM_ALLOWED = 0x2000000; 则可以 因为我无法构建它这个驱动所以我只能在他提供的
https://git.zx2c4.com/wireguard-windows/tree/elevate/doas.go go代码里还原调试这个错误，虽然我再go里通过MAXIMUM_ALLOWED = 0x2000000 成功打开了winlogon.exe 但是它的驱动里还是会再调用一次 错误依然会出现，所以如果有人能联系到驱动作者希望能把这个问题报告给他，或者有更好的方法解决这个打开winlogon.exe 无权限的问题可以留言给我。

声明我运行的程序以及获取到了管理员权限，而且这个问题只会出现我其中的一台电脑上，并且我再issues搜到跟我一样出现这个问题的朋友，我相信这个问题是会在部分用户机器上重现。

**Comment by ghost** [comment]
`Windows 10 x64 20H2 19042.964`

测试正常

**Comment by ghost** [comment]
也许你可以尝试手动更新 `wintun.dll` 吧

[下载地址](https://www.wintun.net/builds/wintun-0.10.3.zip)

将其中的 `wintun\bin\amd64\wintun.dll` 替换到 Netch 目录到即可

**Comment by dongzhaosheng73** [comment]
> 也许你可以尝试手动更新 `wintun.dll` 吧
> 
> [下载地址](https://www.wintun.net/builds/wintun-0.10.3.zip)
> 
> 将其中的 `wintun\bin\amd64\wintun.dll` 替换到 Netch 目录到即可

已经替换了 最新的wintun驱动 依然是通用的结果 而且我用 tun2sock最新版本依旧是这样 
现在可以确定的是这句在我的电脑上会返回没有权限 
go代码通过修改为MAXIMUM_ALLOWED = 0x2000000 替换PROCESS_QUERY_INFORMATION可以正常拿到句柄
所以我推断驱动这里应该也可以操作
![image](https://user-images.githubusercontent.com/18590318/116662895-538de800-a9d1-11eb-8258-142c93fde358.png)

**Comment by ghost** [comment]
那就没了，等上游修，咱正常

**Comment by dongzhaosheng73** [comment]
> 那就没了，等上游修，咱正常

我想也是。。。不过我正研究 编译这个wintun驱动 如果我成功编译并修复这个问题 我会回来反馈的

**Comment by ghost** [comment]
重装系统解决 99% 的问题

**Comment by dongzhaosheng73** [comment]
> 重装系统解决 99% 的问题

好不容用抓到个现象机 不搞清楚就重装系统太浪费了

**Comment by dongzhaosheng73** [comment]
> 重装系统解决 99% 的问题
HI 我虽然没有编译驱动但是我 解决了启动问题 我写了一个win服务 然后权限给到system 就可以成功安装tun网卡了 如果你能解决将进程本身权限提升至system 我想这个问题就可以解决了 ，但是可能winservers更简单一些

**Comment by dongzhaosheng73** [comment]
> 重装系统解决 99% 的问题


HI 我虽然没有编译驱动但是我 解决了启动问题 我写了一个win服务 然后权限给到system 就可以成功安装tun网卡了 如果你能解决将进程本身权限提升至system 我想这个问题就可以解决了 ，但是可能winservers更简单一些

**Comment by dongzhaosheng73** [comment]
https://github.com/py7hagoras/GetSystem  这个项目可以将指定拥有系统权限的进程的权限继承给自己的启动程序

**Comment by dongzhaosheng73** [comment]
> 重装系统解决 99% 的问题
https://github.com/py7hagoras/GetSystem  不行虽然拿到了带有system权限的句柄 但是到启动的时候还是会被拒绝访问 目前看来只有win服务可以解决这问题了 因为win服务本身就是system权限
