### ISSUE TITLE
Bypass Lan and China模式无法启动

### ISSUE THREAD

**Issue by Shadow3945** [netchx/netch#632]
### 错误描述

无法使用绕过局域网和中国大陆模式

### 复现步骤

1.打开netsh
2.模式选Bypass Lan and China
3.点启动

### 日志

[2021/5/1 17:15:29][INFO] 版本: NetchX/Netch@1.8.3
[2021/5/1 17:15:29][INFO] 主程序 SHA256: a727e7c99c5c208cf97216ae59c6f640ad0fb73316ce61f7661ee885ef483495
[2021/5/1 17:15:31][INFO] Github 最新发布版本: 1.8.3
[2021/5/1 17:15:31][INFO] 目前是最新版本
[2021/5/1 17:15:32][INFO] 启动主控制器: Socks5 [2]Bypass LAN and China
[2021/5/1 17:15:32][INFO] 出口 网关 地址：10.77.23.254
[2021/5/1 17:15:32][INFO] 出口适配器：WLAN {24A1E107-62F1-4A00-BD2B-EFCF30CC4115} Intel(R) Wireless-AC 9560 160MHz, index: 7
[2021/5/1 17:15:32][INFO] 自带 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/5/1 17:15:32][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/5/1 17:15:42][ERROR] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Netch.Models.TunAdapter..ctor()
   at Netch.Controllers.TUNController.Start(Mode& mode)
   at Netch.Controllers.TUNController.Netch.Controllers.IModeController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at Netch.Controllers.MainController.Start(Server server, Mode mode)

### 操作环境

```txt
操作系统：windows10 LTSC
软件版本：1.8.3
```

### 额外信息

![image](https://user-images.githubusercontent.com/61302211/116777795-e9dd0f00-aaa0-11eb-8983-438cb3ad7929.png)
![image](https://user-images.githubusercontent.com/61302211/116777803-f2cde080-aaa0-11eb-968b-95b717c13960.png)

**Comment by chsbuffer** [comment]
尝试一下 [Action 构建](https://github.com/NetchX/Netch/actions/)

**Comment by Shadow3945** [comment]
> 尝试一下 [Action 构建](https://github.com/NetchX/Netch/actions/)

一样
```
[2021/5/1 22:06:00][INFO] 版本: NetchX/Netch@1.8.3
[2021/5/1 22:06:00][INFO] 主程序 SHA256: 83cec0f2543f23ffecbaaf4d69e5fffd933ae8a7ed34ff755171b92a3f4a8065
[2021/5/1 22:06:06][INFO] Github 最新发布版本: 1.8.3
[2021/5/1 22:06:06][INFO] 目前是最新版本
[2021/5/1 22:06:30][INFO] 启动主控制器: Socks5 [2]Bypass LAN and China
[2021/5/1 22:06:30][INFO] 出口 网关 地址：10.77.23.254
[2021/5/1 22:06:30][INFO] 出口适配器：WLAN {24A1E107-62F1-4A00-BD2B-EFCF30CC4115} Intel(R) Wireless-AC 9560 160MHz, index: 7
[2021/5/1 22:06:30][INFO] 自带 wintun.dll Hash: c7be044de240c1f7f06f539fcc9869140403807cbc6a8c34374cc72840e6c41a
[2021/5/1 22:06:30][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/5/1 22:06:41][ERROR] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Netch.Utils.NetworkInterfaceUtils.Get(Int32 interfaceIndex)
   at Netch.Models.Adapter.TunAdapter..ctor()
   at Netch.Controllers.TUNController.Start(Mode& mode)
   at Netch.Controllers.TUNController.Netch.Interfaces.IModeController.Start(Mode& mode)
   at Netch.Controllers.MainController.StartMode(Mode mode)
   at Netch.Controllers.MainController.Start(Server server, Mode mode)
```

**Comment by Shadow3945** [comment]
重启了一下好了，抱歉
