### ISSUE TITLE
设置->WinTUN->去掉使用自定义DNS  启动失败

### ISSUE THREAD

**Issue by avboy1337** [netchx/netch#758]
### 错误描述

设置->WinTUN->去掉使用自定义DNS  启动失败
最新编译的aiodns.bin

### 复现步骤

设置->WinTUN->去掉使用自定义DNS
启动

### 日志

C:\Users\Administrator\Desktop\netch-1.8.8\Netch\bin\x64\Release\Netch.exe
[2021-09-13 09:02:18][Information] 自带 wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2021-09-13 09:02:18][Information] 系统 wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2021-09-13 09:02:18][Information] Stop Main Controller
[2021-09-13 09:02:18][Error] Unhandled Exception When Start MainController
System.Exception: AioDNS start failed.
   at Netch.Controllers.DNSController.StartAsync()
   at Netch.Controllers.TUNController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)

### 操作环境

```txt
windows 10 Professinal workstation 19043.928
```

### 额外信息

![image](https://user-images.githubusercontent.com/5463104/133009751-03781da3-81dd-4bbc-a7a4-bb193cae1898.png)

**Comment by chsbuffer** [comment]
最新编译的 aiodns.bin 指什么？
从 main 分支编译的 AioDNS?
master 分支可能并不支持 main 分支 AioDNS

**Comment by cutecr** [comment]
如果你想使用 main 分支的 aiodns 模块

自行适配
