### ISSUE TITLE
process mode not working

### ISSUE THREAD

**Issue by testermania** [netchx/netch#771]
### Describe the bug

process mode not working

### To Reproduce

1.9.1 working but 1.9.2 udp associated problem.

![bug](https://user-images.githubusercontent.com/61498468/137493636-1c0b133a-0087-4617-bc6d-771274bcecbd.png)

### Log

```
[2021-10-15 16:14:47][Information] Netch Version: NetchX/Netch@1.9.2
[2021-10-15 16:14:47][Information] OS: Microsoft Windows NT 10.0.22000.0
[2021-10-15 16:14:47][Information] SHA256: b67aa78a55375b13d5c37c1f6428d7aa600d30da0a3b6ca96d45b08b5951f994
[2021-10-15 16:14:52][Debug] Running Processes: 
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe
C:\Users\Administrator\Downloads\Netch\Netch.exe
[2021-10-15 16:17:43][Information] Start MainController: Socks5 [0]chrome
[2021-10-15 16:17:43][Information] Built-in  netfilter2 driver version: 1.6.1.7
[2021-10-15 16:17:43][Information] Installed netfilter2 driver version: 
[2021-10-15 16:17:43][Information] Install netfilter2 driver
[2021-10-15 16:17:43][Information] Install netfilter2 driver finished
[2021-10-15 16:17:43][Information] Net traffic processes: (6688)Netch
[2021-10-15 16:19:12][Information] Stop Main Controller
[2021-10-15 16:19:15][Error] MainController Stop Error
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Netch.Controllers.MainController.StopAsync()
[2021-10-15 16:19:44][Information] Start MainController: Socks5 [0]ssh
[2021-10-15 16:19:44][Information] Built-in  netfilter2 driver version: 1.6.1.7
[2021-10-15 16:19:44][Information] Installed netfilter2 driver version: 1.6.1.7
[2021-10-15 16:19:44][Information] Net traffic processes: (6688)Netch
[2021-10-15 16:19:57][Information] Stop Main Controller
[2021-10-15 16:20:00][Error] MainController Stop Error
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Netch.Controllers.MainController.StopAsync()
```

### Environment

```txt
OS: Microsoft Windows NT 10.0.22000.0
Netch Version: NetchX/Netch@1.9.2
```

**Comment by chsbuffer** [comment]
Please provide reproduction steps

**Comment by ghost** [comment]
We have tested the latest Redirector. The results show that everything is functioning normally

Please provide useful steps to reproduce before opening this issue

**Comment by testermania** [comment]
@cutecr try naive or hysteria local socks5 127.0.0.1:1080 not working with 1.9.2 process mode. I haven't tried bypass lan mode.

![error](https://user-images.githubusercontent.com/61498468/137585848-34a460cb-63ca-4bd2-9324-e53fdfb23d09.png)

**Comment by ghost** [comment]
MUST be your server error. We confirmed that Socks5 UDP associate in shadowsocksr-windows is works

**Comment by testermania** [comment]
> MUST be your server error. We confirmed that Socks5 UDP associate in shadowsocksr-windows is works

no 1.9.1 working fine with same server.

![error](https://user-images.githubusercontent.com/61498468/137594542-1260a8cb-583d-4d29-8d11-83f13ae52219.png)

**Comment by ghost** [comment]
Please use Wireshark to capture packets for our analysis

**Comment by testermania** [comment]
> Please use Wireshark to capture packets for our analysis

Do you admit there is a problem? still invalid issue.

**Comment by ghost** [comment]
I have already said that we found no problems in our tests

Please provide valid data to prove that there is indeed a problem and can help us fix this problem

**Comment by netch-org** [comment]
If you can't provide valid data (e.g. Wireshark packet capture) that our Socks5 handshake is indeed the problem, then please shut up !

As @cutecr said, we've tested Socks5 on other servers and it works fine

**Comment by testermania** [comment]
> Socks5 el sıkışmamızın gerçekten sorun olduğuna dair geçerli veriler sağlayamıyorsanız (örneğin Wireshark paket yakalama), o zaman lütfen çenenizi kapayın!
> 
> @cutecr'ın dediği gibi, Socks5'i diğer sunucularda test ettik ve gayet iyi çalışıyor
you shut up. 

What proof are you looking for? You control it with Wireshark packet capture. After 1.9.2 people started to have problems. proof proof proof stupid brat.
