### ISSUE TITLE
win7不能启动  驱动签名问题

### ISSUE THREAD

**Issue by M014** [netchx/netch#8]
log：[2019/6/28 22:03:40] 当前语言：zh-CN
[2019/6/28 22:03:43] System.InvalidOperationException: Cannot start service netfilter2 on computer '.'. ---> System.ComponentModel.Win32Exception: Windows 无法验证此文件的数字签名。某软件或硬件最近有所更改，可能安装了签名错误或损毁的文件，或者安装的文件可能是来路不明的恶意软件。
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Netch.Controllers.NFController.Start(Server server, Mode mode)
[2019/6/28 22:03:43] 注册驱动失败，返回值：NF_STATUS_FAIL
[2019/6/28 22:03:43] System.InvalidOperationException: Cannot stop netfilter2 service on computer '.'. ---> System.ComponentModel.Win32Exception: 服务尚未启动。
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Stop()
   at Netch.Controllers.NFController.Stop()

**Comment by ghost** [comment]
你好，已结案，这边我在虚拟机安装了 Win7 操作系统测试没有问题

镜像来自 MSDN，通过百度网盘离线，PanDownload 多线程下载，SHA1 校验正确

通过 VMware 快速安装后我对系统进行了以下处理：
1. 安装了火绒，并把补丁全部打上了
2. Visual C++ 运行库合集
3. .NET Framework 4.8
4. Bandizip 用于解压 7z 压缩包

现在是运行正常的
![图片](https://user-images.githubusercontent.com/52200558/60351940-67ddb400-99f9-11e9-86ce-02c154e04224.png)
![图片](https://user-images.githubusercontent.com/52200558/60351959-7035ef00-99f9-11e9-8a20-b34137b7c7a1.png)
![图片](https://user-images.githubusercontent.com/52200558/60352021-93f93500-99f9-11e9-9f67-10c93361b890.png)
