### ISSUE TITLE
部分节点订阅无法更新

### ISSUE THREAD

**Issue by laoleic4** [netchx/netch#814]
### 错误描述

使用多协议订阅无法正常订阅成功，单独协议的可以成功订阅

### 复现步骤

1.打开Netch软件
2.点击订阅
3.点击管理订阅
4.填写多协议订阅链接和备注
5.点击添加
6.点击更新服务器
7.弹出从xxx更新了0个服务器

### 日志

[2022-03-29 21:14:33][Information] Netch Version: NetchX/Netch@1.9.5
[2022-03-29 21:14:33][Information] OS: Microsoft Windows NT 10.0.19044.0
[2022-03-29 21:14:36][Information] Github latest release: 1.9.2
[2022-03-29 21:14:36][Information] Already the latest version
[2022-03-29 21:14:36][Information] SHA256: 1dfe88318e200facfe9b20177ff966465b4c2ddc121e354666f17cba5a71560a
[2022-03-29 21:14:36][Information] System Language: zh-CN
[2022-03-29 21:14:36][Debug] Running Processes: 
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files (x86)\Common Files\Protexis\License Service\PsiService_2.exe
C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\PopBlock.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\Program Files\Bonjour\mDNSResponder.exe
C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
C:\Program Files\NVIDIA Corporation\ShadowPlay\nvsphelper64.exe
C:\Program Files\Realtek\WifiAutoInstall\WifiAutoInstallSrv.exe
D:\Program Files (x86)\Internet Download Manager\IDMan.exe
D:\Program Files (x86)\SogouInput\11.6.0.5419\SogouCloud.exe
D:\Program Files (x86)\Tencent\QQ\Bin\QQ.exe
D:\Program Files (x86)\Tencent\QQ\Bin\QQApp.exe
D:\Program Files (x86)\Tencent\QQ\Bin\QQExternal.exe
D:\Program Files (x86)\ToDesk\ToDesk_Service.exe
D:\Program Files (x86)\ToDesk\ToDesk.exe
D:\Program Files (x86)\VMware\VMware Workstation\vmware-authd.exe
D:\Program Files (x86)\VMware\VMware Workstation\vmware-hostd.exe
F:\Netch\Netch.exe
[2022-03-29 21:14:36][Debug] Third-party Drivers:
CimFS [CimFS]()
	C:\Windows\system32\drivers\CimFS.sys
VMware hcmon [VMware hcmon](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\hcmon.sys
Huorong Internet Security Devmon Kext [Huorong Internet Security Devmon Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\hrdevmon_win10.sys
Huorong Network Security Firewall Core Kext (WFP) [Huorong Network Security Firewall Core Kext (WFP)](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\hrwfpdrv_win10.sys
IDMWFP [IDMWFP](Copyright © 1999 - 2018 Tonec Inc.)
	C:\Windows\system32\DRIVERS\idmwfp.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
Showshock Softnology Generic Driver [Showshock Softnology Generic Driver]()
	\??\C:\Windows\SysWOW64\DRIVERS\ssgdio64.sys
Steam Streaming Microphone [Steam Streaming Microphone]()
	C:\Windows\system32\drivers\SteamStreamingMicrophone.sys
Steam Streaming Speakers [Steam Streaming Speakers]()
	C:\Windows\system32\drivers\SteamStreamingSpeakers.sys
Huorong Network Security Core Kext [Huorong Network Security Core Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\sysdiag_win10.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\drivers\vmci.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetuserif.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2018 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmx86.sys
[2022-03-29 21:15:31][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:15:38][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:15:41][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:15:44][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:15:46][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:15:53][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:17:48][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:18:47][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:19:03][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:19:40][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:21:35][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-03-29 21:36:16][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)

### 操作环境

```txt
操作环境：Windows 10 Pro 21H2 X64
软件版本：1.9.5
```

### 额外信息

![QQ截图20220329214440](https://user-images.githubusercontent.com/56494512/160625479-beebd2fc-4c9b-4a89-ac45-6c9cca50a567.png)

**Comment by AmazingDM** [comment]
订阅格式不规范或者订阅内容为非已支持协议
https://github.com/netchx/netch/issues?q=%E8%AE%A2%E9%98%85
