### ISSUE TITLE
同一个节点  在除了1.9.6版本以外的任何版本都工作正常

### ISSUE THREAD

**Issue by MurasameCyan** [netchx/netch#837]
### 错误描述

节点后端为xray v1.5.3/1.5.5/1.5.7
ss协议正常  
vless vmess trojan节点在1.9.6版本(其余版本正常)均无法使用

![image](https://user-images.githubusercontent.com/50967145/173002226-b1101354-5c57-43e0-a307-ebaff7899d18.png)
![image](https://user-images.githubusercontent.com/50967145/173002234-d66b405c-a6ed-4f19-a30f-d54d09041464.png)

![image](https://user-images.githubusercontent.com/50967145/173002309-dd7272ed-483f-4e1f-a694-6716dcbc6ad9.png)

### 复现步骤

1.打开1.9.6版本netch
2.连接任意xray后端 vless vmess trojan节点

### 日志

[2022-06-10 13:52:04][Information] Netch Version: NetchX/Netch@1.9.6
[2022-06-10 13:52:04][Information] OS: Microsoft Windows NT 10.0.22000.0
[2022-06-10 13:52:05][Information] SHA256: /
[2022-06-10 13:52:05][Information] System Language: zh-CN
[2022-06-10 13:52:05][Debug] Running Processes: 
/
[2022-06-10 13:52:05][Debug] Third-party Drivers:
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdgpio2.sys
AMD GPIO Client Driver [AMD GPIO Client Driver]((C)2012-2016 Advanced Micro Devices, INC.)
	C:\Windows\system32\drivers\amdgpio3.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2020 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdpsp.sys
dump_wmimmc [dump_wmimmc]()
	\??\S:\Program Files (x86)\pso2jp\pso2_bin\GameGuard\dump_wmimmc.sys
LdVBoxDrv [LdVBoxDrv]()
	\??\C:\Program Files\ldplayerbox\LdVBoxDrv.sys
LgdCatcher [LgdCatcher]()
	C:\Windows\system32\drivers\LgdCatcher.sys
LgdCatcherTdi [LgdCatcherTdi]()
	C:\Windows\system32\drivers\LgdCatcherTdi.sys
Logitech G HUB Virtual Bus Enumerator Driver [Logitech G HUB Virtual Bus Enumerator Driver](Copyright © Logitech, Inc. 2021)
	C:\Windows\system32\drivers\logi_joy_bus_enum.sys
Logitech G HUB Translation Layer Driver [Logitech G HUB Translation Layer Driver](Copyright © Logitech, Inc. 2021)
	C:\Windows\system32\drivers\logi_joy_xlcore.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
npf [npf](Copyright © 2010-2013 Riverbed Technology, Inc. Copyright © 2005-2010 CACE Technologies. Copyright © 1999-2005 NetGroup, Politecnico di Torino.)
	C:\Windows\system32\drivers\npf.sys
Razer Control Service [Razer Control Service](Copyright © 2021 Razer Inc. All rights reserved)
	C:\Windows\system32\drivers\RzCommon.sys
Razer 008a Service [Razer 008a Service](Copyright © 2020 Razer Inc. All rights reserved)
	C:\Windows\system32\drivers\RzDev_008a.sys
Scp Virtual Bus Driver [Scp Virtual Bus Driver](Copyright Â© 2012, 2013 Scarlet.Crush Productions. All rights reserved.)
	C:\Windows\system32\drivers\ScpVBus.sys
TAP-Windows Adapter V9 [TAP-Windows Adapter V9](OpenVPN Technologies, Inc.)
	C:\Windows\system32\drivers\tap0901.sys
Nefarius Virtual Gamepad Emulation Service [Nefarius Virtual Gamepad Emulation Service]((C) 2016-2020 Nefarius Software Solutions e.U.)
	C:\Windows\system32\drivers\ViGEmBus.sys
XLGuard Driver [XLGuard Driver]()
	C:\Windows\system32\drivers\XLGuard.sys
Xunlei WFP Driver [Xunlei WFP Driver]()
	C:\Windows\system32\drivers\xlwfp.sys
Nox Limited Service [Nox Limited Service]()
	\??\C:\Program Files (x86)\Bignox\BigNoxVM\RT\YSDrv.sys
[2022-06-10 13:52:06][Information] Github latest release: 1.9.6
[2022-06-10 13:52:06][Information] Already the latest version
[2022-06-10 13:52:21][Information] Start MainController: VLESS [0]pso2ngs
[2022-06-10 13:52:22][Debug] Server Information: VLESS none + grpc + xudp + gun
[2022-06-10 13:52:22][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 13:52:22][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 13:52:22][Information] Net traffic processes: (8928)v2ray-sn
[2022-06-10 13:52:40][Information] Stop Main Controller
[2022-06-10 13:52:51][Information] Start MainController: VLESS [0]pso2ngs
[2022-06-10 13:52:51][Debug] Server Information: VLESS none + grpc + xudp + gun
[2022-06-10 13:52:51][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 13:52:51][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 13:52:51][Information] Net traffic processes: (14432)v2ray-sn
[2022-06-10 13:54:40][Information] Stop Main Controller
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:06][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:07][Error] Parse servers from share link error
System.UriFormatException: Text is not a URI
   at Netch.Utils.ShareLink.GetUriScheme(String text)
   at Netch.Utils.ShareLink.ParseUri(String& text)
   at Netch.Utils.ShareLink.ParseText(String text)
[2022-06-10 13:56:33][Information] Start MainController: VLESS [0]pso2ngs
[2022-06-10 13:56:33][Debug] Server Information: VLESS none + grpc + xudp + gun
[2022-06-10 13:56:33][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 13:56:33][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 13:56:33][Information] Net traffic processes: (15884)v2ray-sn
[2022-06-10 14:00:38][Information] Stop Main Controller
[2022-06-10 14:00:47][Information] Start MainController: SS [0]pso2ngs
[2022-06-10 14:00:48][Debug] Server Information: SS aes-128-gcm + 
[2022-06-10 14:00:48][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 14:00:48][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 14:00:48][Information] Net traffic processes: (2340)v2ray-sn
[2022-06-10 14:01:04][Information] Stop Main Controller
[2022-06-10 14:01:08][Information] Start MainController: VLESS [0]pso2ngs
[2022-06-10 14:01:08][Debug] Server Information: VLESS none + grpc + xudp + gun
[2022-06-10 14:01:08][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 14:01:08][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 14:01:08][Information] Net traffic processes: (16100)v2ray-sn
[2022-06-10 14:01:14][Information] Stop Main Controller
[2022-06-10 14:01:27][Information] Start MainController: SS [0]pso2ngs
[2022-06-10 14:01:27][Debug] Server Information: SS aes-128-gcm + 
[2022-06-10 14:01:28][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 14:01:28][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 14:01:28][Information] Net traffic processes: (4432)v2ray-sn
[2022-06-10 14:02:11][Information] Stop Main Controller
[2022-06-10 14:02:20][Information] Start MainController: VMess [0]pso2ngs
[2022-06-10 14:02:20][Debug] Server Information: VMess aes-128-gcm + grpc + xudp + none
[2022-06-10 14:02:20][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 14:02:20][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 14:02:20][Information] Net traffic processes: (6076)v2ray-sn
[2022-06-10 14:02:26][Information] Stop Main Controller
[2022-06-10 14:02:34][Information] Start MainController: Trojan [0]pso2ngs
[2022-06-10 14:02:34][Debug] Server Information: Trojan 
[2022-06-10 14:02:34][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-06-10 14:02:34][Information] Installed netfilter2 driver version: 1.6.3.0
[2022-06-10 14:02:34][Information] Net traffic processes: (4120)v2ray-sn
[2022-06-10 14:03:15][Information] Stop Main Controller

V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
2022/06/10 14:02:34 [Warning] V2Ray 5.0.14 started
2022/06/10 14:02:34 [Warning] [4225654682] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2022/06/10 14:02:34 [Warning] [1030679984] app/dispatcher: default route for udp:198.211.120.59:3478

### 操作环境

```txt
win11 x64 10.0.22000
```

**Comment by DinuruSeniya** [comment]
I also have the same issue, it's because Netch doesn't have a field to set the ALPN to h2 when using VLESS+GRPC.
Therefore it won't connect.

我也有同样的问题，这是因为 Netch 在使用 VLESS+GRPC 时没有将 ALPN 设置为 h2 的字段。
因此它不会连接。我也有同样的问题，这是因为 Netch 在使用 VLESS+GRPC 时没有将 ALPN 设置为 h2 的字段。
因此它不会连接。
