### ISSUE TITLE
1.9.6 升级 1.9.7 报错：请求的名称有效，但找不到请求的数据

### ISSUE THREAD

**Issue by CHN-STUDENT** [netchx/netch#863]
### 错误描述

1.9.6 升级 1.9.7 报错：请求的名称有效，但找不到请求的数据

### 复现步骤

检查新版本，点击升级按钮。

### 日志

[2022-06-27 12:34:24][Information] Netch Version: NetchX/Netch@1.9.6
[2022-06-27 12:34:24][Information] OS: Microsoft Windows NT 10.0.19044.0
[2022-06-27 12:34:25][Information] SHA256: 1a92f3ec4192a1653b96f3a765e8b60d1d9fc6db355b5d2129a71c42c3497a2b
[2022-06-27 12:34:25][Information] System Language: zh-CN
[2022-06-27 12:34:25][Debug] Third-party Drivers:
CimFS [CimFS]()
	C:\Windows\system32\drivers\CimFS.sys
DDDriver [DDDriver]((c) Dell Technologies. All rights reserved.)
	C:\Windows\system32\drivers\dddriver64Dcsa.sys
VMware hcmon [VMware hcmon](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\hcmon.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
Npcap Packet Driver (NPCAP) [Npcap Packet Driver (NPCAP)](Copyright (c) 2021, Insecure.Com LLC.  All rights reserved.)
	C:\Windows\system32\DRIVERS\npcap.sys
Sadp Driver (NPF) [Sadp Driver (NPF)]()
	\??\D:\sadp\SADP\npf64.sys
ProxifierDrv [ProxifierDrv](Copyright (C) 2018-2020 Initex. All rights reserved.)
	C:\Windows\system32\DRIVERS\ProxifierDrv.sys
seewo - Virtual Monitor Stub [seewo - Virtual Monitor Stub](Copyright (C) 2018. Guangzhou Shirui Electronics. All Rights Reserved.)
	C:\Windows\system32\drivers\VMonitorBus_amd64.sys
USBPcap Capture Service [USBPcap Capture Service]((c) 2013-2020 Tomasz Mon)
	C:\Windows\system32\DRIVERS\USBPcap.sys
VirtualBox NDIS 6.0 Miniport Service [VirtualBox NDIS 6.0 Miniport Service](Copyright (C) 2009-2022 Oracle Corporation)
	C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys
VirtualBox NDIS6 Bridged Networking Service [VirtualBox NDIS6 Bridged Networking Service](Copyright (C) 2009-2022 Oracle Corporation)
	C:\Windows\system32\DRIVERS\VBoxNetLwf.sys
VirtualBox Service [VirtualBox Service](Copyright (C) 2009-2022 Oracle Corporation)
	C:\Windows\system32\DRIVERS\VBoxSup.sys
VirtualBox USB Monitor Service [VirtualBox USB Monitor Service](Copyright (C) 2009-2022 Oracle Corporation)
	C:\Windows\system32\DRIVERS\VBoxUSBMon.sys
Sharing Camera [Sharing Camera](Copyright (C) 2018. Guangzhou Shirui Electronics. All Rights Reserved.)
	C:\Windows\system32\DRIVERS\VirtualCamera_amd64.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2019 VMware, Inc.)
	C:\Windows\system32\drivers\vmci.sys
VMware Input Filter and Injection Driver (vmkbd) [VMware Input Filter and Injection Driver (vmkbd)](Copyright © 1998-2020 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmkbd.sys
VMware Virtual Ethernet Adapter Driver [VMware Virtual Ethernet Adapter Driver](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetadapter.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetuserif.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmx86.sys
vSockets Virtual Machine Communication Interface Sockets driver [vSockets Virtual Machine Communication Interface Sockets driver](Copyright © 1998-2020 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vsock.sys
WiMan Service [WiMan Service]()
	C:\Windows\system32\DriverStore\FileRepository\wiman.inf_amd64_420e5de7a8744212\WiManH\WiManH.sys
MpKslfb069c82 [MpKslfb069c82]()
	\??\C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{323FCD65-0A3E-4D46-8FBB-9AB54E1A6E01}\MpKslDrv.sys
[2022-06-27 12:34:26][Debug] Running Processes: 
C:\Program Files (x86)\Browny02\BrYNSvc.exe
C:\Program Files (x86)\CIB_PBPlugin\ocPlugin\MHServer.exe
C:\Program Files (x86)\CIB_PBPlugin\ocPlugin\ServiceDeamon.exe
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files (x86)\Common Files\Steam\steamservice.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
c:\Program Files (x86)\Dell Digital Delivery Services\Dell.D3.WinSvc.exe
C:\Program Files (x86)\Dell\UpdateService\ServiceShell.exe
C:\Program Files (x86)\HP\HP Software Update\hpwuschd2.exe
C:\Program Files (x86)\HP\StatusAlerts\bin\HPStatusAlerts.exe
C:\Program Files (x86)\LocalServiceComponents\LocalServiceControl.exe
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
C:\Program Files\Bonjour\mDNSResponder.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files\Dell\DellDataVault\DDVCollectorSvcApi.exe
C:\Program Files\Dell\DellDataVault\DDVDataCollector.exe
C:\Program Files\Dell\DellDataVault\DDVRulesProcessor.exe
C:\Program Files\Dell\DellOptimizer\DellOptimizer.exe
C:\Program Files\Dell\SARemediation\agent\DellSupportAssistRemedationService.exe
C:\Program Files\Dell\SupportAssistAgent\bin\SupportAssistAgent.exe
C:\Program Files\Dell\SupportAssistAgent\PCD\SupportAssist\Dsapi.exe
C:\Program Files\Everything\Everything.exe
C:\Program Files\ExpressConnect\ECDBWM.exe
C:\Program Files\ExpressConnect\ECDBWMService.exe
C:\Program Files\ExpressConnect\ExpressConnect.exe
C:\Program Files\ExpressConnect\ExpressConnectAnalyticsService.exe
C:\Program Files\ExpressConnect\ExpressConnectNetworkService.exe
C:\Program Files\ExpressConnect\ExpressConnectService.exe
C:\Program Files\Ext2Fsd\Ext2Srv.exe
C:\Program Files\HPPrintScanDoctor\HPPrintScanDoctorService.exe
C:\Program Files\MacType\MacTray.exe
C:\Program Files\MacType\mt64agnt.exe
C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqld.exe
C:\Program Files\Synergy\synergyc.exe
C:\Program Files\Synergy\synergyd.exe
C:\Users\ITC\AppData\Local\IdeaShareKey\IdeaShareService.exe
C:\Users\ITC\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\ThumbPlayer\3366\extracted\WeChatPlayer.exe
C:\Users\ITC\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\WMPFRuntime\4520\extracted\runtime\WeChatAppEx.exe
C:\Users\ITC\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\732\extracted\WeChatBrowser.exe
D:\Netch\Netch.exe
D:\oray\SunloginClient\SunloginClient.exe
D:\Program Files (x86)\Kingsoft\WPS Office\11.8.2.8506\office6\wps.exe
D:\Program Files (x86)\Steam\bin\cef\cef.win7x64\steamwebhelper.exe
D:\Program Files (x86)\Steam\Steam.exe
D:\Program Files (x86)\Tencent\WeChat\WeChat.exe
D:\vmware\vmware-tray.exe
D:\vmwareb\vmware-converter-a.exe
D:\vmwareb\vmware-converter.exe
[2022-06-27 12:34:27][Information] Github latest release: 1.9.7
[2022-06-27 12:34:27][Information] Found newer version
[2022-06-27 12:34:35][Warning] Download Update File Failed
System.Net.WebException: 请求的名称有效，但是找不到请求的类型的数据。 (github.com:443)
 ---> System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。 (github.com:443)
 ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Netch.Utils.WebUtil.DownloadFileAsync(HttpWebRequest req, String fileFullPath, IProgress`1 progress)
   at Netch.Utils.WebUtil.DownloadFileAsync(HttpWebRequest req, String fileFullPath, IProgress`1 progress)
   at Netch.Forms.MainForm.NewVersionLabel_Click(Object sender, EventArgs e)
[2022-06-27 12:34:45][Information] Github latest release: 1.9.7
[2022-06-27 12:34:45][Information] Found newer version
[2022-06-27 12:34:47][Warning] Download Update File Failed
System.Net.WebException: 请求的名称有效，但是找不到请求的类型的数据。 (github.com:443)
 ---> System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。 (github.com:443)
 ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Netch.Utils.WebUtil.DownloadFileAsync(HttpWebRequest req, String fileFullPath, IProgress`1 progress)
   at Netch.Utils.WebUtil.DownloadFileAsync(HttpWebRequest req, String fileFullPath, IProgress`1 progress)
   at Netch.Forms.MainForm.NewVersionLabel_Click(Object sender, EventArgs e)
[2022-06-27 12:35:17][Information] Github latest release: 1.9.7
[2022-06-27 12:35:17][Information] Found newer version
[2022-06-27 12:35:20][Warning] Download Update File Failed
System.Net.WebException: 请求的名称有效，但是找不到请求的类型的数据。 (github.com:443)
 ---> System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。 (github.com:443)
 ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Netch.Utils.WebUtil.DownloadFileAsync(HttpWebRequest req, String fileFullPath, IProgress`1 progress)
   at Netch.Utils.WebUtil.DownloadFileAsync(HttpWebRequest req, String fileFullPath, IProgress`1 progress)
   at Netch.Forms.MainForm.NewVersionLabel_Click(Object sender, EventArgs e)

### 操作环境

```txt
[2022-06-27 12:34:24][Information] Netch Version: NetchX/Netch@1.9.6
[2022-06-27 12:34:24][Information] OS: Microsoft Windows NT 10.0.19044.0
```

**Comment by CHN-STUDENT** [comment]
搜了下，可能是 DNS 被污染的问题，请问作者后期是否代理下载更新的想法解决？
