### ISSUE TITLE
启动Netch提示2801端口是系统保留端口

### ISSUE THREAD

**Issue by MirrorCY** [netchx/netch#913]
### 错误描述

已检查2801端口未被占用，重启前正常使用

### 复现步骤

打开Netch
点击启动

### 日志

[2022-08-23 23:29:57][Information] Netch Version: NetchX/Netch@1.9.7
[2022-08-23 23:29:57][Information] OS: Microsoft Windows NT 10.0.22000.0
[2022-08-23 23:29:57][Information] Start MainController: SS [0]Steam Games (with Steam)
[2022-08-23 23:29:57][Debug] Server Information: SS aes-256-gcm + 
[2022-08-23 23:29:57][Information] Stop Main Controller
[2022-08-23 23:29:57][Error] MainController Stop Error
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Netch.Controllers.Guard.StopGuardAsync()
   at Netch.Controllers.Guard.StopGuardAsync()
   at Netch.Controllers.MainController.StopAsync()

### 操作环境

```txt
win11工作站22000.856
```

### 额外信息

![image](https://user-images.githubusercontent.com/37006258/186201608-5acf5df4-9ef6-4af9-9b59-810419462206.png)

**Comment by MirrorCY** [comment]
卸载Npcap后重启恢复正常
