### ISSUE TITLE
无法启动 Access to the path 'netfilter2.sys' is denied

### ISSUE THREAD

**Issue by foanet** [netchx/netch#914]
### 错误描述

无法启动netch，启动报错
UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
已经修改netfilter2.sys文件权限，无效
以管理员启动，无效

### 复现步骤

1.打开netch
2.启动
3.报错

### 日志

[2022-08-25 18:43:32][Information] Netch Version: NetchX/Netch@1.9.7
[2022-08-25 18:43:32][Information] OS: Microsoft Windows NT 10.0.19044.0
[2022-08-25 18:43:33][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2022-08-25 18:43:33][Information] System Language: zh-CN
[2022-08-25 18:43:33][Debug] Running Processes: 
C:\Program Files (x86)\Common Files\Autodesk Shared\AdskLicensing\Current\AdskLicensingService\AdskLicensingService.exe
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files (x86)\Common Files\Steam\steamservice.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.30.07191\LenovoSmartService.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.30.07191\SmartEngineHost.exe
C:\Program Files (x86)\Lenovo\SmartEngine\1.0.30.07191\SmartEngineHost64.exe
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
C:\Program Files (x86)\Steam\bin\cef\cef.win7x64\steamwebhelper.exe
C:\Program Files (x86)\Steam\steam.exe
C:\Program Files\Autodesk\AdODIS\V1\Setup\AdskAccessServiceHost.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files\Microsoft SQL Server\90\Shared\sqlwriter.exe
C:\Program Files\Side Effects Software\Houdini Server\hserver.exe
C:\Program Files\Side Effects Software\License Server\sesinetd.exe
C:\Program Files\Softdeluxe\Free Download Manager\fdm.exe
C:\Program Files\Softdeluxe\Free Download Manager\helperservice.exe
C:\Program Files\Softdeluxe\Free Download Manager\wenativehost.exe
C:\Program Files\Tablet\Wacom\Wacom_Tablet.exe
C:\Program Files\Tablet\Wacom\Wacom_TabletUser.exe
C:\Program Files\Tablet\Wacom\Wacom_TouchUser.exe
C:\Program Files\Tablet\Wacom\Wacom_UpdateUtil.exe
C:\Program Files\Tablet\Wacom\WacomHost.exe
C:\Program Files\Tablet\Wacom\WTabletServicePro.exe
C:\Program Files\The Foundry\LicensingTools7.1\bin\RLM\rlm.foundry.exe
C:\ProgramData\Dolby\DAX3\RADARHOST\DSRHost.exe
C:\Users\liya\AppData\Local\Microsoft\OneDrive\OneDrive.exe
C:\Users\liya\Downloads\Netch\Netch\Netch.exe
C:\v2rayN-Core\v2rayN.exe
C:\v2rayN-Core\wv2ray.exe
[2022-08-25 18:43:33][Debug] Third-party Drivers:
Lenovo Virtual Power Controller Driver [Lenovo Virtual Power Controller Driver]()
	C:\Windows\system32\drivers\AcpiVpc.sys
Audio Coprocessr Driver for DSP [Audio Coprocessr Driver for DSP](© Advanced Micro Devices. All rights reserved.)
	C:\Windows\system32\DriverStore\FileRepository\amdacpbus.inf_amd64_36c81572f42cc25a\amdacpbus.sys
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdgpio2.sys
AMD I2C Controller Service [AMD I2C Controller Service](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdi2c.sys
amdkmdag [amdkmdag](Copyright (C) 1998-2012 Advanced Micro Devices, Inc.)
	C:\Windows\system32\DriverStore\FileRepository\u0359763.inf_amd64_cbe903b159d3b969\B359805\amdkmdag.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2020 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdpsp.sys
CimFS [CimFS]()
	C:\Windows\system32\drivers\CimFS.sys
Huorong Internet Security Devmon Kext [Huorong Internet Security Devmon Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\hrdevmon_win10.sys
Huorong Network Security Firewall Core Kext (WFP) [Huorong Network Security Firewall Core Kext (WFP)](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\hrwfpdrv_win10.sys
Huorong Network Security Core Kext [Huorong Network Security Core Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\sysdiag_win10.sys
netfilter2 [netfilter2](Copyright ? NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
[2022-08-25 18:43:34][Information] Start MainController: VMess [0]AMD Radeon
[2022-08-25 18:43:34][Debug] Server Information: VMess auto + ws + xudp + none + none
[2022-08-25 18:43:35][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-08-25 18:43:35][Information] Installed netfilter2 driver version: 1.6.0.2
[2022-08-25 18:43:35][Information] Update netfilter2 driver
[2022-08-25 18:43:35][Information] Uninstall netfilter2
[2022-08-25 18:43:35][Information] Stop Main Controller
[2022-08-25 18:43:35][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)
[2022-08-25 18:44:54][Information] Start MainController: VMess [0]AMD Radeon
[2022-08-25 18:44:54][Debug] Server Information: VMess auto + ws + xudp + none + none
[2022-08-25 18:44:54][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-08-25 18:44:54][Information] Installed netfilter2 driver version: 1.6.0.2
[2022-08-25 18:44:54][Information] Update netfilter2 driver
[2022-08-25 18:44:54][Information] Uninstall netfilter2
[2022-08-25 18:44:54][Information] Stop Main Controller
[2022-08-25 18:44:54][Error] Unhandled Exception When Start MainController
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\drivers\netfilter2.sys' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Netch.Controllers.NFController.UninstallDriver()
   at Netch.Controllers.NFController.CheckDriver()
   at Netch.Controllers.NFController.StartAsync(Socks5Server server, Mode mode)
   at Netch.Controllers.MainController.StartAsync(Server server, Mode mode)

V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
2022/08/25 18:44:54 [Warning] V2Ray 5.0.14 started

### 操作环境

```txt
操作系统 ：Windows 10 专业版 21H2 19044.1889 Windows Feature Experience Pack 120.2212.4180.0
软件版本: 1.9.7
```

### 额外信息

![12](https://user-images.githubusercontent.com/37451232/186645478-21717b48-97ba-43a2-aaf6-043aa78035e8.PNG)

**Comment by opaque111** [comment]
我也遇到了这个问题，有什么解决方案吗，使用的是1.9.7和1.9.6版本
