### ISSUE TITLE
提示DLL缺失，到底是什么DLL缺失呢?

### ISSUE THREAD

**Issue by YI--** [netchx/netch#938]
### 错误描述

Netch启动， 提示DLL缺失！

### 复现步骤

下载 1.9.7 
打开Netch.exe
输入订阅地址
点击启动

提示DLL缺失，装了其他版本也这样

### 日志

[2022-10-01 18:42:44][Information] Github latest release: 1.9.7
[2022-10-01 18:42:44][Information] Already the latest version
[2022-10-01 18:42:53][Information] Start MainController: Trojan [0]AMD Radeon
[2022-10-01 18:42:53][Debug] Server Information: Trojan
[2022-10-01 18:42:53][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2022-10-01 18:42:53][Information] Installed netfilter2 driver version: 1.6.0.7
[2022-10-01 18:42:53][Information] Update netfilter2 driver
[2022-10-01 18:42:53][Information] Uninstall netfilter2
[2022-10-01 18:42:53][Information] Stop Main Controller
[2022-10-01 18:42:53][Error] MainController Stop Error
System.DllNotFoundException: Dll was not found.
   at Netch.Interops.Redirector.aio_free()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Netch.Controllers.MainController.StopAsync()

### 操作环境

```txt
操作系统：Windows 10 专业版 21H2 19044.2006
版本：1.9.7
```

### 额外信息

![图片](https://user-images.githubusercontent.com/10511182/193406047-888b8063-deef-4b30-9ee7-db67ae839960.png)

**Comment by canmengxian** [comment]
.NET 6.0安装了吗

**Comment by YI--** [comment]
> .NET 6.0安装了吗

5.0 6.0 都装了，主要是不提示到底缺失什么DLL库，我把源代码下载用VS编译运行之启动后一直提示缺少tun2socks 或者Redirector，提示缺少tun2socks看上去应该是规则不对导致的，Redirector缺失是搞不懂了；
目前版本退到1.5.0是可以正常使用的，1.5.0之后所有版本对于我来说都不能使用，再其他地方看了下好像有人也反馈这个问题，但是没有最终的答复；

感谢你的回复，目前来说我还是使用其他方式吧；

这个问题我关闭了，感谢回复

**Comment by canmengxian** [comment]
> > .NET 6.0安装了吗
> 
> 5.0 6.0 都装了，主要是不提示到底缺失什么DLL库，我把源代码下载用VS编译运行之启动后一直提示缺少tun2socks 或者Redirector，提示缺少tun2socks看上去应该是规则不对导致的，Redirector缺失是搞不懂了； 目前版本退到1.5.0是可以正常使用的，1.5.0之后所有版本对于我来说都不能使用，再其他地方看了下好像有人也反馈这个问题，但是没有最终的答复；
> 
> 感谢你的回复，目前来说我还是使用其他方式吧；
> 
> 这个问题我关闭了，感谢回复

那有可能是你电脑系统问题了，我在win10，11都没有碰到什么问题。
