### ISSUE TITLE
Windows系统代理关闭、且模式为`Bypass LAN`或`Bypass LAN and Vivox`，5-10秒后闪退

### ISSUE THREAD

**Issue by imldy** [netchx/netch#969]
### 错误描述

Windows系统代理开启、代理IP地址和端口只要有内容就不闪退

## 第一种情况：
1. Windows系统代理关闭
2. 启动netch
3. 选择`Bypass LAN`模式
4. 点击右下角启动
5. 等待左下角显示`状态：已启动`
6. 5-10秒后闪退
## 第二种情况：
或者前期手动设置系统代理，启动并运行一段时间后，手动关闭系统代理，5-10秒后闪退
## 第三种情况（涉及到第三方软件，很奇怪）：
或者前期打开clash.mini(此软件自动设置系统代理)，启动并运行一段时间后，通过clash.mini取消系统代理（或者关闭此软件），5-10秒后闪退。但是若是手动设置代理，则不会闪退。

### 日志
```
[2022-11-28 23:05:20][Debug] Third-party Drivers:
Dokan1 [Dokan1]()
	\??\C:\Program Files\Huawei\PCManager\dokan1.sys
DroidCam Virtual Audio [DroidCam Virtual Audio](Copyright (C) 2010)
	C:\WINDOWS\system32\drivers\droidcam.sys
DroidCam Source 3 [DroidCam Source 3]((C) 2019)
	C:\WINDOWS\system32\DriverStore\FileRepository\droidcamvideo.inf_amd64_47e18363cbf3dfe0\droidcamvideo.sys
EasyTether Network Adapter [EasyTether Network Adapter](© 2010-2015 Mobile Stream)
	C:\WINDOWS\system32\drivers\easytthrx.sys
VMware hcmon [VMware hcmon](Copyright © 1998-2020 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\hcmon.sys
Huorong Internet Security Devmon Kext [Huorong Internet Security Devmon Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\hrdevmon_win10.sys
Huorong Network Security Firewall Core Kext (WFP) [Huorong Network Security Firewall Core Kext (WFP)](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\hrwfpdrv_win10.sys
hwnetstat [hwnetstat]()
	\??\C:\Program Files\Huawei\PCManager\WFPDriver.sys
HUAWEI MateBook Os2EC [HUAWEI MateBook Os2EC]()
	\??\C:\Program Files\Huawei\PCManager\HwOs2EC10x64.sys
IDMWFP [IDMWFP](Copyright © 1999 - 2018 Tonec Inc.)
	C:\WINDOWS\system32\DRIVERS\idmwfp.sys
LgdCatcher [LgdCatcher]()
	C:\WINDOWS\system32\drivers\LgdCatcher.sys
LgdCatcherTdi [LgdCatcherTdi]()
	C:\WINDOWS\system32\drivers\LgdCatcherTdi.sys
Npcap Packet Driver (NPCAP) [Npcap Packet Driver (NPCAP)](Copyright (c) 2020, Insecure.Com LLC.  All rights reserved.)
	C:\WINDOWS\system32\DRIVERS\npcap.sys
SbieDrv [SbieDrv]()
	\??\D:\Program Files\Sandboxie\SbieDrv.sys
Huorong Network Security Core Kext [Huorong Network Security Core Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\sysdiag_win10.sys
TAP-Windows Adapter V9 [TAP-Windows Adapter V9](OpenVPN Technologies, Inc.)
	C:\WINDOWS\system32\drivers\tap0901.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2019 VMware, Inc.)
	C:\WINDOWS\system32\drivers\vmci.sys
VMware Virtual Ethernet Adapter Driver [VMware Virtual Ethernet Adapter Driver](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmnetadapter.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmnetuserif.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2020 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmx86.sys
vSockets Virtual Machine Communication Interface Sockets driver [vSockets Virtual Machine Communication Interface Sockets driver](Copyright © 1998-2020 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vsock.sys
Vstor2 MntApi 2.0 Driver (shared) [Vstor2 MntApi 2.0 Driver (shared)](Copyright © 1998-2009 VMware, Inc.)
	C:\WINDOWS\system32\drivers\vstor2-mntapi10-shared.sys
WDTDrv [WDTDrv](Huawei Device. All rights reserved.)
	C:\WINDOWS\system32\Drivers\WDTDrv.sys
xfilter [xfilter](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\xfilter.sys
Wintun [Wintun](Copyright © 2018-2021 WireGuard LLC. All Rights Reserved.)
	C:\WINDOWS\system32\DRIVERS\wintun.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\netfilter2.sys
[2022-11-28 23:05:20][Information] Start MainController: SS [2]Bypass LAN
[2022-11-28 23:05:20][Debug] Server Information: SS aes-256-gcm + 
[2022-11-28 23:05:21][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-11-28 23:05:21][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-11-28 23:05:23][Warning] Get releases failed
System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Netch.Utils.WebUtil.DownloadStringAsync(HttpWebRequest req, Encoding encoding)
   at Netch.Controllers.UpdateChecker.CheckAsync(Boolean isPreRelease)
[2022-11-28 23:05:36][Information] Net traffic processes: (19168)v2ray-sn
此处日志停止刷新，25分左右闪退
```

### 操作环境

```txt
操作系统：Windows 11 家庭版 22H2 22621.819
软件版本：1.9.7
```

**Comment by imldy** [comment]
也有可能是AioDNS的问题
